export const DESC_API = 'DESC_API';
export const PORT_STATS_API = 'PORT_STATS_API';
export const FLOW_STATS_API = 'FLOW_STATS_API';
export const FLOW_AGG_STATS_API = 'FLOW_AGG_STATS_API';
export const FLOW_AGG_GRAPH_API = 'FLOW_AGG_GRAPH_API';
export const PORT_GRAPH_API = 'PORT_GRAPH_API';